### ISSUE TITLE
Placement of report

### ISSUE THREAD

**Issue by laszewsk** [cybertraining-dsc/fa20-523-337#1]
the report must be in subdir project/project.md you put it in main dir. We will not review your document if you do not place it in the right location

please remabe Project to project

**Comment by dataML007** [comment]
Hello Professor - Thanks for the comments. I have placed the project.md appropriately. However, when I click on the link 

https://cybertraining-dsc.github.io/report/fa20-523-337/project/project/ , I get 404 not found error message. However, my edit is working fine. I am trying to fix it, but none of them seem to be working now. Could you please let me know a good place to check?

Thanks,
Balaji

**Comment by laszewsk** [comment]
this link is a nonfunctional link your report is in

https://github.com/cybertraining-dsc/fa20-523-337

as usual. the link for edit is in the report and the one on the right-hand side is not yet working. use the one in the report. Please see the template

**Comment by laszewsk** [comment]
could it be that at one point you had a capital letter in your project name ?

If so github is confused as gthub does not allow for distinction.

It will probably take me hours to fix that. But before I do this work for you, I need to confirm./

**Comment by laszewsk** [comment]
oh I see my first comment even says it. Too bad, this will take a significant amount of time on my side. please next time follow our directions

**Comment by dataML007** [comment]
Hello Professor - I apologize for the trouble. I checked this morning, it seems like the link is working now Thanks for helping me to fix this issue. I will ensure not to happen in the future.

Again, thanks a lot for helping me to fix this issue. 

Regards,
Balaji
