### ISSUE TITLE
partner

### ISSUE THREAD

**Issue by laszewsk** [cybertraining-dsc/fa20-523-337#4]
you should have asked to add your partner with full write access to the github

now it looks like that one person did a project instead of two

please provide githubid and TA or gregor will add 
your partner needs to show contributions from now on

**Comment by dataML007** [comment]
Hello Professor - Good Evening I wasn't aware that I need to add my partner Github. Because this was a group project, and already let TA know my partner name, we used the same repo to commit and update comments.  How do we ensure, he gets credit for the project as well because he has contributed to this project as well?

**Comment by laszewsk** [comment]
All class related things are discussed in piazza as github is open source.

I already explained how he can get access. He needs to use piaza to communicate with me.

**Comment by laszewsk** [comment]
Messages were sent 10 days ago to him via piazza. Unfortunately, we have not heard back .... he needs to use piazza to communicate with us. Only messages to instructors will be known to everyone.

**Comment by laszewsk** [comment]
WHat is his github id ? Whay can he not let everyone know. The TA has not informed me.

**Comment by laszewsk** [comment]
contributions are visible here: https://github.com/cybertraining-dsc/fa20-523-337/graphs/contributors

**Comment by dataML007** [comment]
Thanks a lot for helping us. I hope he was able to communicate and we have his GID as well. Shall we close this issue?

**Comment by hz6yc3** [comment]
Sorry again Professor for the confusion with the GitHub id! Thanks a lot again for helping out today morning!
